### ISSUE TITLE
[Unity] NotificationServices.RegisterForNotifications causing NullReferenceException in Parse?

### ISSUE THREAD

**Issue by andymads** [parse-community/Parse-SDK-dotNET#44] opened 2015-10-20 14:04 UTC
I've started getting a NullReferenceException somewhere in Parse but I don't think it's caused by something I'm explicitly doing.

I believe it occurs when I register for notifications in Unity because as soon as I make this call it occurs.

NotificationServices.RegisterForNotifications(NotificationType.Alert|NotificationType.Badge|NotificationType.Sound);

I get this printed in the output just before the exception:

didRegisterForRemoteNotificationsWithDeviceToken

NullReferenceException: A null value was found where an object instance was required.
  at Parse.ParseInstallation.getLocaleIdentifier () [0x00000] in <filename unknown>:0 
  at Parse.ParseInstallation.SetAutomaticValues () [0x00000] in <filename unknown>:0 
  at Parse.ParseInstallation.SaveAsync (System.Threading.Tasks.Task toAwait, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at Parse.ParseObject+<>c__DisplayClass18.<SaveAsync>b__17 (System.Threading.Tasks.Task toAwait) [0x00000] in <filename unknown>:0 
  at Parse.Internal.TaskQueue.Enqueue[Task](System.Func`2 taskStart, CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at Parse.ParseObject.SaveAsync (CancellationToken cancellationToken) [0x00000] in <filename unknown>:0 
  at Parse.ParseObject.SaveAsync () [0x00000] in <filename unknown>:0 
  at Parse.ParseInitializeBehaviour.<Awake>b__0 (System.Byte[] deviceToken) [0x00000] in <filename unknown>:0 
  at Parse.PlatformHooks+<>c__DisplayClass28.<RegisterDeviceTokenRequest>b__26 () [0x00000] in <filename unknown>:0 
  at Parse.PlatformHooks+<RunDispatcher>d__2e.MoveNext () [0x00000] in <filename unknown>:0 
UnityEngine.Debug:Internal_LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Parse.<RunDispatcher>d__2e:MoveNext()

**Comment by richardjrossiii** [comment] 2015-10-20 19:42
Thanks for the report. It would appear that unity is returning null for `CultureInfo.CurrentCulture`, which is super weird. I'll look into it.

**Comment by richardjrossiii** [comment] 2015-10-21 00:36
I just tested on iOS 8.4 with Unity 5.2.1, and I have been unable to reproduce this crash.

Would you mind sharing more information about the devices you're seeing these crashes on, and what version of Unity you're using?

**Comment by andymads** [comment] 2015-10-21 08:03
Ok, more info.

Firstly, my device is running iOS 9.0.1 and I'm using Unity 5.2.1p4.

Also the issue is not a crash, just an exception being logged, and the app continues to run. And I'm now sure it's caused by the call to NotificationServices.RegisterForNotifications.

However, I've just updated to Parse 1.6.1 from 1.5.5 and now I don't get the exception but I do get some interesting messages instead. So it does look like Parse is getting the message that remote notifications have been registered and then doing something it shouldn't be.

**didRegisterForRemoteNotificationsWithDeviceToken: < my token here >**

**get_localNotificationCount can only be called from the main thread.**

**Constructors and field initializers will be executed from the loading thread when loading a scene.**

**Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.**

**Comment by andymads** [comment] 2015-10-28 08:42
I have provided more info. Please respond.

**Comment by skumancer** [comment] 2016-02-05 05:19
I am having this problem as well. Removed the calls to `RegisterForNotifications` and the NullRef didn't happen again.

Definitely need a fix for this. I'm running Parse 1.7 + Unity 5.3.2

**Comment by richardjrossiii** [comment] 2016-02-05 19:30
This will most likely be fixed in 1.8.0 along with the refactoring of all of the Unity push notification code.

**Closed** 2020-06-28 16:23 UTC
Labels: Unity, bug, needs investigation
