### ISSUE TITLE
Unity 2018.2 Application.isWebPlayer error in ParseInitializeBehaviour...

### ISSUE THREAD

**Issue by brendanlk** [parse-community/Parse-SDK-dotNET#294] opened 2018-08-01 05:10 UTC
Unity 2018.2 has removed the **UnityEngine.Application.isWebPlayer** property which is causing a runtime error. This is the full error:

```
MissingMethodException: Method not found: 'UnityEngine.Application.get_isWebPlayer'.
Parse.ParseClient.Initialize (Configuration configuration)
Parse.ParseClient.Initialize (System.String applicationId, System.String dotnetKey, System.String serverURL)
Parse.ParseInitializeBehaviour.Initialize ()
Parse.ParseInitializeBehaviour.Awake ()
```

**Comment by brendanlk** [comment] 2018-08-07 22:59
I'm happy to do a fix for this myself, but it appears that **Parse.ParseInitializeBehaviour** is no longer in the repository? Or it it being held elsewhere?

**Comment by brendanlk** [comment] 2018-08-07 23:53
I know there used to be, but it looks like a lot has changed. I was going by the downloads available [here](https://github.com/parse-community/Parse-SDK-dotNET/releases/tag/1.7.0), but these downloads and source seem ancient. I'm not sure what the new workflow is for unity.

**Comment by flovilmart** [comment] 2018-08-07 23:54
I’m not sure either. To be honest, dotNet has been left out over the years, unfortunately as no new maintainer arised. If you’re using this framework, let me know what I can do

**Comment by brendanlk** [comment] 2018-08-08 00:00
Thanks for the quick replies.
Our project is still depending on Parse and it's important that we upgrade unity to 2018.2.
I tried compiling the latest master, and it all compiled fine. But when I put the Parse.dll into the project, Unity can't detect the Parse namespace. I'm not super familiar with building dlls, but if I can get it working, I could easily fix it myself I think.

**Comment by flovilmart** [comment] 2018-08-08 00:03
@thefanatr any idea?

**Comment by flovilmart** [comment] 2018-08-08 00:03
I know everything was revamped a few months ago, but I’m not sure where things are

**Comment by keerthik** [comment] 2018-08-08 23:29
I was going to work on a PR for this fix after our current project release sprint.

The folder with Unity-specific scripts appear to have been lost in master. From 1.7.0, ParseInitializeBehaviour and ParseInstallation.Unity.cs are present [here](https://github.com/parse-community/Parse-SDK-dotNET/tree/1.7.0/Parse/Public/Unity). You can probably copy and use these files as is after the fix to address the Unity error, if anyone wants to address this before  I have the time to...

**Comment by flovilmart** [comment] 2018-08-09 01:57
@keerthik since this PR https://github.com/parse-community/Parse-SDK-dotNET/pull/284 I believe the project was refactored into 100% dotNet standard. I'm not sure what in means for Unity support. If you can provide guidance I'd love us to maintain the unity compatibility.

**Comment by TheFanatr** [comment] 2018-08-09 17:07
Hi.
I wrote a solution to this, explaining the issue and how to solve it, but I closed the tab and now it's gone. If only I could pay attention to what I am doing.

**Comment by TheFanatr** [comment] 2018-08-09 18:04
Basically, the issue here is that the OP is using an old version of Parse which references an outdated UnityEngine SDK assembly, and specifically uses a property called `isWebPlayer`, which is supposed to return a value for whether or not the code is running in the Unity Web Player. Because the Unity Web Player no longer exists, the aforementioned property no longer exists in newer versions of the assembly. That is why there are errors in the Unity Editor. In order to use the a compiled copy of the master branch of this repository, the Unity Editor needs to be configured for .NET Standard 2.0 support. This can be done by opening the Unity Player Settings in the Inspector via Navigating through `Edit > Project Settings > Player` and scrolling down to the `Configuration` header in the Inspector, and changing the setting for `Scripting Runtime Version` to `.NET 4.x Equivalent` then restarting the Unity Editor, then changing the setting for `Api Compatibility Level` to `.NET Standard 2.0` under the same header. This change should allow the Unity Editor to see the compiled Parse SDK and make it possible to be referenced in the game's source code.

**Comment by brendanlk** [comment] 2018-08-09 23:41
@TheFanatr So you're saying that I can keep the current (old) version I have, or should I use the latest commit on master? Following the steps you provided (with the old version) seems to give this weird error whenever I reference System.Threading.Tasks:

**The type 'Task' exists in both 'Parse.Unity, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'**

It seems like the .net tasks in the dll are conflicting with the tasks in unity?

**Comment by TheFanatr** [comment] 2018-08-10 12:53
@brendanlk If you configure Unity for .NET Standard 2.0 support I would recommend you use the latest master branch, as the old Parse SDK contained .NET Framework libraries added post-framework-2.0 in order for the Parse codebase to work properly in Unity because in the default configuration it uses a .NET Framework 2.0 API subset, whereas Parse needs Framework 4.x I believe. These extra libraries are no longer needed as .NET Standard 2.0 already includes them. Just compile the SDK and add it to your assets.

**Comment by TheFanatr** [comment] 2018-08-10 13:05
Basically, the Task API and some others from post-2.0 .NET Framework were integrated into the Unity-specific version of the Parse SDK because Unity didn't have them by default. In .NET Standard 2.0 API Subset mode, Unity includes all that by default. Basically, the code you write targets .NET Franework 4.6, but the project references some kind of .NET Standard 2.0 compatibility provision assembly.

**Comment by TheFanatr** [comment] 2018-08-10 13:06
@flovilmart I'all take a look at he docs and maybe update them later today.

**Comment by TheFanatr** [comment] 2018-08-10 13:08
I'll try take a look at the docs and update them if needed later today.

**Comment by brendanlk** [comment] 2018-08-13 02:02
@TheFanatr I have upgraded our unity project to .NET 4.x (Mono) and compiled the latest master. After fixing some compiler issues (on our end) we are getting this error:

**Unloading broken assembly Assets/Plugins/Parse/Parse.dll, this assembly can cause crashes in the runtime**

I'm not sure how unity knows that it will cause an issue. But when running the game and calling Parse.ParseUser.LogInAsync(), I'm getting this error:

**TypeLoadException: Could not load type of field 'Parse.Common.Internal.StorageController:fileTask' (2) due to: Could not load file or assembly 'StandardStorage, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:StandardStorage, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null) signature:<none>
Parse.Core.Internal.ParseCorePlugins.get_InstallationIdController () (at <f027885a9c59450184a0b30ec0c9aee2>:0)
Parse.Core.Internal.ParseCorePlugins.get_CommandRunner () (at <f027885a9c59450184a0b30ec0c9aee2>:0)
Parse.Core.Internal.ParseCorePlugins.get_UserController () (at <f027885a9c59450184a0b30ec0c9aee2>:0)
Parse.ParseUser.get_UserController () (at <f027885a9c59450184a0b30ec0c9aee2>:0)
Parse.ParseUser.LogInAsync (System.String username, System.String password, System.Threading.CancellationToken cancellationToken) (at <f027885a9c59450184a0b30ec0c9aee2>:0)
Parse.ParseUser.LogInAsync (System.String username, System.String password) (at <f027885a9c59450184a0b30ec0c9aee2>:0)**

**Comment by TheFanatr** [comment] 2018-08-13 22:10
Import a compiled copy of StandardStorage as well, along with all external dependencies, and it should work. Eventually, a Parse package can be added to the Unity Asset Store containing all the needed assemblies and resources to make life easier, but until then I believe you have to reference all of Parse's dependencies (recursive, of course) that are not part of .NET Standard 2.0's coverage and not referenced by Unity manually. I am currently attempting to make a CRUD testing app for the Parse .NET SDK in Unity in order to verify that it does fully work on the platform, but due to the lack of an closely-accessible internet connection, I haven't been able to work on it much. I will release it along with any fixes needed to Parse and/or dependencies I have control over within the next few days. I believe there may be another issue with saving data on special platforms and/or targets such as when using Parse with Unity targeting Unity WebGL or with Blazor, but I have yet to confirm either.

**Comment by fayyadsufyan** [comment] 2018-09-02 14:09
@TheFanatr Can you provide more details about the inclusion of those external dependence? I am stuck at "this assembly can cause crashes in the runtime"

Currently using Unity 2018.2.1 trying to upgrade an old Unity 5.6 Parse project.
Your help is very appreciated

**Comment by thibautvdu** [comment] 2018-09-14 13:45
Any input on this ?
I tried several things, building it without the references to the depreciated functions, etc. with no luck.
The functions (SignUpAsync, etc.) never call back.

**Comment by brendanlk** [comment] 2018-09-21 00:49
I'm still having trouble getting this working too. Is it only @TheFanatr working on this?

**Comment by TheFanatr** [comment] 2018-09-21 01:35
I don't know who else is working on this at the moment. I will look into getting a sample running, and will post it here.

**Comment by flovilmart** [comment] 2018-09-21 01:49
@TheFanatr you're the reference person now! and a maintainer if you want to :)

**Comment by TheFanatr** [comment] 2018-09-25 07:03
@flovilmart Ok, cool. Thanks.

To update everyone on the situation here, it would seem that because of the way that Unity is handling assembly generation for in-editor playtest builds, the needed family of properties within the value of the `Microsoft.Extensions.PlatformAbstractions.PlatformService.Default.Application` property are returning `null`, causing the `Path.Combine` operation to fail silently, making the execution crash when the null value result is passed to the constructor for `FileInfo`, which manages file storage in my modified version of `Parse` that no longer depends on `StandardStorage`. The current master branch of this repository would also likely not work because the same problem of not being able to find the name and version of the assembly would be present. I am unsure as to if `StandardStorage` would fix this issue, but it is essentially redundant nonetheless because .NET Standard 2.0 already contains APIs specifically included to handle platform-agnostic file operations. I have found a workaround and am attempting to implement a fix. You can see my progress on my fork of `Parse-SDK-dotNET`. After this, I will attempt to integrate a `LiveQuery` implementation, as well as supporting a server-side use case for the Parse .NET SDK via making alternative `ParseUser` interaction structures available as dependency injections (one class would have it implemented statically like it is now, and another would have it instantiable so that multiple user logins can be loaded concurrently based on the session token stored in the browser's local storage, for ASP.NET Core usage). That last suggestion was based on my personal need, for a project I am working on, so if I end up just not using Parse, it may not ever get implemented.

**Comment by TheFanatr** [comment] 2018-09-25 08:46
It would seem that no matter what I do, if I try to reflectively extract metadata about the assembly, the operation will fail, and using the Unity-provided reflection utilities, the only result I get is the name `Assembly-CSharp`, which is the default scripting project name. After some searching, it would seem that some hard-coded values for the Unity Application's version, name, and company are embedded into the assembly, and they still seem to be inaccessible via reflection, but are accessible via the Unity Engine SDK's `Application` class. In order to accommodate this, and to fix any erroring within Unity-compiled projects when using the Parse .NET SDK, I will likely have the cache location be configurable, or at least make it possible to set the values for version and name that the caching system should prefer to use. If I only make the metadata values configurable, then I will likely change the path to be the simply the location of `System.Environment.SpecialFolder.LocalApplicationData`, with the file name `app-1.0.0.0.pcache` or `cacheIdentifier.pcache` with `cacheIdentifier` being a settable cache identification property, in order to basically completely eradicate storage path collisions with unrelated same-named programs that use the same caching folder structure.

The following is the Unity-specific code to successfully generate the persistent storage path that the Parse SDK cannot currently generate for Unit.

```csharp
System.IO.Path.GetFullPath(System.IO.Path.Combine(System.Environment.GetFolderPath(System.Environment.SpecialFolder.LocalApplicationData), UnityEngine.Application.productName, UnityEngine.Application.version));
```

Note that for this to work, the Unity Player must be configured for .NET Standard 2.0 support, otherwise all of the referenced types must be referenced manually if they are not included by your target .NET Framework API coverage.

**Comment by TheFanatr** [comment] 2018-09-25 08:51
I also need to update the documentation on this, as it seems to be very outdated.

**Comment by flovilmart** [comment] 2018-09-25 11:27
Thanks for the update! This is really appreciated.

**Comment by TheFanatr** [comment] 2018-09-26 09:02
This is proving significantly more tedious than previously anticipated because registering subclasses also writes data to the cache, so `ParseClient.Initialize(ParseClient.Configuration configuration)` cannot be trusted to be the first time the persistent storage path needs to be used, so I have to come up with a default and once the actual one is initialized, I have to copy it's contents to the new path.

**Comment by TobiasPott** [comment] 2018-10-19 10:48
I'm a bit in a hurry at the moment but will prepare a pull request later this day or next week.
In my fork of this repository I've targeted the file access when using Parse inside a Unity application on mobile platforms like Android and iOS as we use Parse for one of our backend structure and the communication with it.
You might take a look at it if you like: https://github.com/TobiasPott/Parse-SDK-dotNET

**Comment by qruxtapose** [comment] 2018-10-20 03:57
Hi @TobiasPott 

Thanks for providing your fork. I was actually able to build the project without UnityEngine.dll. Maybe there is something I'm missing here but nothing in the project looks to be Unity specific (and as such doesn't seem to work with Unity). Any ideas?

**Comment by qruxtapose** [comment] 2018-10-21 21:30
@TobiasPott No problem at all! Thanks for looking into it

**Comment by TobiasPott** [comment] 2018-10-22 07:36
Back in office right now and checked git.
Missed the push to the remote, sorry for that.

You may check the master branch now and find the changes I've made last week.
Sorry for your inconvenience.

If any Unity versions prior to 2018.2 are giving you troubles, just tell me and I bump the backward compatibility up on my ToDo list.

**Comment by TobiasPott** [comment] 2018-10-22 07:39
Hm for unknown reason the website has eaten my comment from 2 min ago -.-

I'm back in office and checked my git.
Missed the push to the remote last week and sorry for your inconvenience.

You may check the master branch for the changes I've mentioned last week.

If you are facing any problems with Unity versions prior 2018.2 don't hesitate to ask and I'll bump backward compatibility up a bit on my ToDo list.

**Comment by TheFanatr** [comment] 2018-10-22 08:34
GitHub is acting up at the moment. I was going to post something important but apparently that's not an option right now because it might get swallowed. FYI: https://status.github.com/messages

**Comment by TobiasPott** [comment] 2018-10-22 10:41
Yeah I've noticed that already and got a bit angry this morning -.- (related to another project)

I've discovered that caching the session is not working properly right now with my changes and currently digging into it for a fix. (hopefully github doesn't eat this one)

**Comment by TobiasPott** [comment] 2018-10-23 06:51
@qruxtapose Have you got it running in an iOS or Android build out of Unity? 
I did get some errors about a "broken assembly" which might cause errors at runtime when using the build from this Parse repository and didn't even get it to initialize on Android (built from Unity).

**Comment by qruxtapose** [comment] 2018-10-23 17:28
@TobiasPott Yes. It's running in Android (built from Unity) but with errors. It does appear to initialize and I'm able to download the Parse.Config just fine. After that it fails my authentication process on Android where it succeeds in Unity editor.

**Comment by TobiasPott** [comment] 2018-10-24 08:36
@qruxtapose got similar issues when using the official repository thus I sticked to @TheFanatr repository.

I'm not yet that deep into Parse to understand the inner workings that good to help with the specific issues but I did some more adjustments on my forked repo to get Unity Editor support and fix caching as it did not work properly on my side..

**Comment by hqMoura** [comment] 2018-11-09 00:07
There is a fix for this?

I still facing the same issue with the webPlayer exception.

**Comment by TobiasPott** [comment] 2018-11-11 16:53
@hqMoura:
What do you mean with "webPlayer" exception, the same as the OP mentioned?
Are you using assemblies build from this repository or where did you get them from?

The latest commit in the master branch does not contain any references to Application.isWebPlayer from UnityEngine.dll anymore and thus should not give any exceptions due to a call to it. This is unless you use an older version or something from the 1.8.0 branch.
As discussed above some issues exists when using the latest commit in this repository within Unity and @TheFanatr has forked it and I did a fork of that repository as I needed a working build for Unity 2018.2
You may take a look at these repositories. (This said, the Parse version in these repositories require your Unity project to support .NET Standard or .NET 4.6).

**Comment by pprwght2** [comment] 2018-11-13 03:02
@TobiasPott
I recompiled your and @TheFanatr solutions

I can't seem to get past initalization ParseClient.Initialize(config);

NullReferenceException: Object reference not set to an instance of an object
Parse.ParseClient+Configuration+VersionInformation..cctor ()

**Comment by TobiasPott** [comment] 2018-11-14 07:49
@pprwght2 
Could you please give us some more information about your setup?
Which Unity version are you using and which of the output assemblies are you using?
Are you using Parse inside the Editor (via Editor-script) or during runtime?
Are you testing in play-mode (in-editor) or with a built application on a target platform?

**Comment by pprwght2** [comment] 2018-11-14 20:03
@TobiasPott 

Unity 2018.2.14f.1, compiled to release build and copied everything under VS Release dir to Assets/Parse,
settings are se to to .NET 4.x Equivalent, API comp Level 4.x

**Comment by pprwght2** [comment] 2018-11-18 01:14
It's working In a .Net console application. In Unity it fails at **ParseClient.Initialize(new ParseClient.Configuration** ...


NullReferenceException: Object reference not set to an instance of an object
Parse.ParseClient+Configuration+VersionInformation..cctor () (at Parse-SDK-dotNET-master/Parse/Public/ParseClient.cs:130)
Rethrow as TypeInitializationException: The type initializer for 'VersionInformation' threw an exception.
Parse.ParseClient.Initialize (Parse.ParseClient+Configuration configuration) (at /Parse-SDK-dotNET-master/Parse/Public/ParseClient.cs:240)
 test.cs+<setupND>c__Iterator13.MoveNext () (at Assets/project/src/test.cs:6198)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at unity/build/Runtime/Export/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
<setupNetworkDataHolder>c__Iterator11:MoveNext() (at Assets/proj/src/test.cs:6174)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)

**Comment by TobiasPott** [comment] 2018-11-20 09:14
Hm could you check if you copied the Parse.dll also?
The output are actually explicit for each platform and Parse.dll is for .NET (outside Unity) Parse.Unity.dll is for Unity runtime (devices, and editor play-mode) Parse.Unity.Editor.dll is for editor scripting.

Remove the Parse.dll as it uses only .NET stuff which is not available in Unity as the way version and application information is gathered is not provided by Unity the way Parse assumes it.
You can leave the Parse.Unity.Editor.dll when you never intend to use Parse from editor scripts.
You may check the platform settings of the Parse.Unity.dll and Parse.Unity.Editor.dll (is required when having the editor dll in your project to avoid ambiguities.

Sorry for the delay, I've forgot to answer yesterday when in office =(

**Comment by pprwght2** [comment] 2018-11-20 10:41
Thanks for answer, using Parse.Unity.dll only, 2018.2.14f.1 runtime in-editor  fails with

NullReferenceException: Object reference not set to an instance of an object
Parse.ParseClient+Configuration+VersionInformation..cctor () (at <4e88660be348469a8ef9bebf9b56de11>:0)
Rethrow as TypeInitializationException: The type initializer for 'VersionInformation' threw an exception.
Parse.ParseClient.Initialize (Parse.ParseClient+Configuration configuration) (at <4e88660be348469a8ef9bebf9b56de11>:0)
testParse.Start () (at Assets/testParse.cs:13)

It's a clean project, only with gameobject attached with C# in Start()

 ParseClient.Initialize(new ParseClient.Configuration
        {
            ApplicationID = appIDString,
            MasterKey = appMasterKey,
            ServerURI = appServerURI
        });

**Comment by TobiasPott** [comment] 2018-11-20 12:33
@pprwght2 Would you mind zipping and sending me your project so I can have a look at it?
Remove all credentials and server information and send me a link as I can't reproduce this issue with a clean project =/ (you might use PM for the link)

**Comment by pprwght2** [comment] 2018-11-20 13:06
zipped unity project 
https://files.fm/u/z46jgp4u

**Comment by TobiasPott** [comment] 2018-11-20 15:57
@pprwght2 There is actually an issue when building the Unity and Unity.Editor assemblies from the repository. 
The assembly in your project is quite different from the one resulting from my local repo.
I'll need to get into this and check what is going wrong when building from a cloned remote repo.

**Comment by pprwght2** [comment] 2018-11-21 05:20
@TobiasPott 
It is working now! Setting compiler flag and copying UnityEngine.dll did it.
One more question, I will now start integrating code into bigger project, you mentioned this:
"I've discovered that caching the session is not working properly right now with my changes and currently digging into it for a fix. (hopefully github doesn't eat this one)".
Would you recommend this repo for production use or is it better to wait for new updates? Thanks again!

**Comment by TobiasPott** [comment] 2018-11-21 09:03
@pprwght2 
I'll push the changes with the compiler flag later this day and will add information about usage and required references to the Readme of my fork.
As far as I can tell caching works now, the statement was an old one and I tackled this issue as we use Parse for production development of an application platform right now.

I'm not 100% sure whether everything what should be cached, is cached but at least user credentials, sessions and configs are (never checked for other stuff yet and I'm unfortunately not that into Parse and everthing it is supposed to do =/).
As far as I can tell there are several TODO comments in this project which might indicate what is actually not working or still needs fiddling. But those I'll need to find more time to take a look at.

**Comment by WalGallen-Baktun** [comment] 2018-11-22 16:35
@TobiasPott 
Hi! I'm trying to build the project using Visual Studio, but I'm getting these errors while trying to open it.

C:\Users\user\Desktop\Parse-SDK-dotNET-master\Parse\Parse.csproj : error  : The SDK 'Microsoft.NET.Sdk' specified could not be found.  C:\Users\user\Desktop\Parse-SDK-dotNET-master\Parse\Parse.csproj

C:\Users\user\Desktop\Parse-SDK-dotNET-master\Parse.Test\Parse.Test.csproj : error  : The SDK 'Microsoft.NET.Sdk' specified could not be found.  C:\Users\user\Desktop\Parse-SDK-dotNET-master\Parse.Test\Parse.Test.csproj

**Comment by lucks** [comment] 2018-11-22 20:38
> 
> 
> @TobiasPott
> It is working now! Setting compiler flag and copying UnityEngine.dll did it.
> One more question, I will now start integrating code into bigger project, you mentioned this:
> "I've discovered that caching the session is not working properly right now with my changes and currently digging into it for a fix. (hopefully github doesn't eat this one)".
> Would you recommend this repo for production use or is it better to wait for new updates? Thanks again!

hi, could you pls share your parse-unity.dll , I have the same issues.

**Comment by lucks** [comment] 2018-11-22 21:42
I'm trying to compile the fork @TobiasPott but not success, "missing Parse.dll" ,

**Comment by TobiasPott** [comment] 2018-11-23 07:59
@WalGallen-Baktun I created a new issue from your response as it does not seem to be directly related to the original topic of this thread (as lot of other things did not unfortunately)

@lucks I don't want to be rude but if you have the same issue as pprwght2 wouldn't his solution solve it for you too?

**Comment by lucks** [comment] 2018-11-23 08:48
My issue is that with you repo, I cannot compile the parse.unity.dll, I installed dotnet sdk 2.1.500, download you repo, then attach the unitengine.dll, then run dotnet restore for the nuget package, but when I try to compile, many System. (String, and others ) not found with the Net 2.0, 
![captura](https://user-images.githubusercontent.com/124778/48934578-384a5480-eeca-11e8-9968-a2d0a88433a4.PNG)

**Comment by TobiasPott** [comment] 2018-11-23 11:35
Ah yes, I got that one few times and was not able to determine what causes it.

Could you try cleaning the whole solution.
Afterwards unloading all projects except the Unity.Parse one and rebuild this one.

I have this issue from time to time and I'm not quite sure how to avoid it as Parse.Unity and Parse.Unity.Editor are only different in one additional compiler symbol.

I need to dig into this one for now, until then I think the above described way should allow you to build the specific projects (adopt to the Parse.Unity.Editor project respectively)

**Comment by pprwght2** [comment] 2018-11-23 12:00
@lucks did you also install

Microsoft.DotNet.PlatformAbstractions
Microsoft.Extensions.PlatformAbstractions
StandardStorage from Nuget

**Comment by TobiasPott** [comment] 2018-11-23 13:09
@lucks Could you please check the [feature/fix-netstandard-system-types-not-found](https://github.com/TobiasPott/Parse-SDK-Unity-NETStandard/tree/feature/fix-netstandard-system-types-not-found) branch of my repository? 

I checked this issue and added build configurations to the solution file instead of using separate project files. When I use the zipped download from github directly, added the UnityEngine.dll to the project folder I could build all assemblies right away.
It would be great if you could test it on your system if this did fix the issue for you too.

To build for Unity select the Debug-Unity or Release-Unity configurations and build your solution (or only the 'Parse' project). If you need to have all assemblies build at once you might setup a batch build (right-click on the solution -> Batch Build...) according to your needs

**Comment by lucks** [comment] 2018-11-23 16:38
hi, @TobiasPott at first instance, download de branch, as zip, then add unityEngine.dll, then select Release-Unity, then compile the solution, but I got the following error:
Severity Code Description Project File Line Status suppressed
Error CS1061 "ParseObject" does not contain a definition for "IsNew" nor is there any accessible "IsNew" extension method that accepts a first argument of type "ParseObject" (missing some using directive or an assembly reference?) Parse.Test C: \ Users \ lucks \ Documents \ visualStudioProjects \ Parse-SDK-Unity-NetStandard-feature-fix-netstandard-system-types-not-found \ Parse.Test \ ObjectTests.cs 242 Active

**Comment by lucks** [comment] 2018-11-23 16:59
Well, just commented and compile again, a think now I have the parse.unity.dll , i going to test in the game, thank you!

**Comment by TobiasPott** [comment] 2018-11-26 07:41
@lucks Yeah this IsNew was a remainder of the previous version from the original repository. I'm not quite there to know whether these are required or not and what the IsNew flag is used for in which situations.

Glad you got it compiling and good luck with your game =)

**Comment by pprwght2** [comment] 2018-11-26 09:22
I am slowly moving stuff to new Parse and Unity. The only problem is if you stuff bunch of StartCouroutines in loop trying to retrieve (first calling Parse and getting url Path successfully) http web images it doesn't work reliable in Unity 2018.14. It worked always in Unity 5.6.5p4, is anyone using other Unity 2018 versions and getting good 'multi-threading' calls results?

**Comment by TobiasPott** [comment] 2018-11-27 11:16
@pprwght2 We are using 2018.2.12 at the moment with the NET Standard 2.0 API compatibility level and the 4.x scripting runtime version. the multi-threading works good enough for us on all target platforms (PC, iOS and Android). 
Instead of Coroutines we are using [async/await](https://docs.microsoft.com/en-us/dotnet/csharp/async) which is available at least since the NET Standard compatibility was introduced into Unity itself. 

You may consider using async and await too. (I can't find the link for Unity where they describe the support for async/await, but it sure does ^^ with 2018.2.x or newer)

**Comment by pprwght2** [comment] 2018-11-28 08:51
Switched to 2018.12.f1, it still didnt work properly under .Net Standard 2.0 but switching to .Net 4.x works everytime.

**Comment by pprwght2** [comment] 2018-11-28 09:02
Well not everrytime, but overall there are less errors than in 2018.2.14, I gonna switch back to .Net Standard 2.0 and try looking into async/wait calls.

One more thing do you have any version suggestions for Parse server version, currently we are running on 2.2.25 but we have an easy option to upgrade up to 2.6.1, 2.7.2, 2.8.1, 2.8.2.

**Comment by pprwght2** [comment] 2018-11-29 14:31
Testing 2.6.1 with Node.js 8.11 (advised by person in database business)

**Comment by fayezsalka** [comment] 2018-12-08 20:47
Ahhh...good old Parse giving us massive head aches. I managed to compile the library from my mac, but it has two problems:

- Task completion callback is inconsistent as mentioned above 
- You can't stack query conditions on top of each other anymore. For example the following doesn't work:

query = ParseObject.GetQuery ("Songs").WhereEqualTo ("Genre", "Classic").WhereEqualTo ("Name", "Beethoven");

Only the last "WhereEqualTo" condition is met. Whereas in older version of Parse Unity both conditions were met. I'm not sure what is going on. Can anyone confirm this issue?

**Comment by TobiasPott** [comment] 2018-12-10 11:06
Actual an different issue as it looks to me, but i never checked that query thing that deep. Could you open a different issue on this, I'll think that will help to keep track of it and have a look asap.

**Comment by pprwght2** [comment] 2018-12-13 14:57
Looks like Unitz 2018.3 with 4.x as default was released, downloading and testing soon.

**Comment by flovilmart** [comment] 2018-12-13 15:01
@TheFanatr @TobiasPott I invited you to the org and therefore you have commit access.

**Comment by TheFanatr** [comment] 2018-12-13 16:41
Hi, I have been quite busy for the past while, and so I have not been able to contribute to this much; sorry about that. For the next couple weeks I can help fix some issues and continue with what I was planning to do. The issue with Unity at the moment is that there is a bug somewhere in their .NET Standard provisioning library that is causing certain operations to inexplicably fail. I was trying to solve this a while ago but never finished. The fork I have on my account contains a partially-refactored version of the source in this repository, specifically with the dependency on all external libraries removed; it complies to one clean assembly that does actually work with Unity without issue. The main problem is at runtime; if Parse is logged in to, the program will crash. This is, of course on a version of Unity from a while ago, so things may have changed. Have there been any developments in creating Unity support?

**Comment by TheFanatr** [comment] 2018-12-13 16:49
Just a side note to anyone trying to include Parse in their Unity projects: if you want to use .NET 4.x API compatibility mode instead of .NET Standard compatibility mode, then you have to provision the difference in API coverage manually, and until you do, Unity will say that the assembly is unsafe and/or doesn't work properly - because it won't - and so it will unload it. Last I checked, Unity's .NET 4.x mode covered Framework 4.5.x or something. Something interesting to note is that switching to .NET Standard mode will keep Unity's base API coverage the same, but automatically provide the aforementioned provisioning assembly.

**Comment by TheFanatr** [comment] 2018-12-13 16:53
I will check with the latest version of Unity later today to see if anything has changed.

**Comment by fayezsalka** [comment] 2018-12-13 17:19
Hello Everyone,

I managed to implement Parse into Unity 2018.2 without using a DLL, meaning that in the future if Unity deprecates some APIs the API updater should take care of it automatically, plus, you can do your own modifications to Parse inside Unity without having to compile a new DLL with each modification.

[https://github.com/fayezsalka/Parse-for-Unity-2018]

Tested with Unity 2018.2.19f1, on iOS and Unity Editor. This implantation doesn't have any of the issues listed above

Usage:

- In Player Settings, make sure to set Scripting Runtime Version to ".NET 4.x Equivalent" and Api Compatibility Level to ".NET 4.x"
- Drop "ParseInitializeBehaviour" prefab into your scene and fill in your Application ID, Dotnetkey and Server URL

**Comment by TheFanatr** [comment] 2018-12-13 17:34
@fayezsalka From inspecting this, it is just the Parse source as an asset package; can you confirm that logging in actually works, as I do not have a test environment set up for 2018.2.18f1. I have been able to get Parse working inside Unity before, but logging in did not work, so that was the limiting factor. Also, just a side note that Parse source from the master branch of this repository does not consume any Unity APIs, so Unity deprecating APIs in the future is essentially inconsequential.

**Comment by fayezsalka** [comment] 2018-12-13 17:48
It's the parse source but with slight modifications so it runs inside Unity without being compiled to DLL.

I can confirm that ParseUser.LogInAsync works in my environment

**Comment by TheFanatr** [comment] 2018-12-13 17:55
Here's an interesting development: the bug in Unity was fixed, so my compiled DLL from my fork works perfectly on the exact same project I used a while ago that didn't work.

**Comment by TheFanatr** [comment] 2018-12-13 17:59
![image](https://user-images.githubusercontent.com/16641853/49957713-834dfb00-febd-11e8-90ce-e54bea041564.png)
![image](https://user-images.githubusercontent.com/16641853/49957757-a5e01400-febd-11e8-818a-5558015fc807.png)
That's just the direct build output from my fork that I copied to a folder in the Unity project. I'm going to try the source currently in the master branch.

**Comment by TheFanatr** [comment] 2018-12-13 18:01
Haven't completely verified, but I think that this issue fixed itself because Unity fixed their libraries.

**Comment by TheFanatr** [comment] 2018-12-13 18:06
@fayezsalka Just out of curiosity, which repo were you working out of when you made the asset package?

**Comment by fayezsalka** [comment] 2018-12-13 18:11
I used the old source code found here: https://github.com/parse-community/Parse-SDK-dotNET/releases/tag/1.7.0

I used It as it had non of the regressions found in the newer repos (at least in my case, queries with more than 100 results worked inconsistently, and staking query conditions on top of each also didn't work, which was a deal breaker)

**Comment by TheFanatr** [comment] 2018-12-13 18:21
@fayezsalka Interesting. Thanks for letting me know about the query stacking and mass-result failure issue; do you know if the same behaviour is experienced outside of Unity?

**Comment by TheFanatr** [comment] 2018-12-15 07:18
@fayezsalka I will open a new issue for this. Initially, though, I haven't been able to confirm your results. I have been able to reliably query a class with 200+ generated entries and limit the results count to various numbers over 100, with the operation still completing successfully. Do you have a specific test case you can provide? I feel that it is quite important that something as fundamental as querying works.

**Comment by vaspotapov** [comment] 2019-02-04 08:49
> Unity 2018.2 has removed the **UnityEngine.Application.isWebPlayer** property which is causing a runtime error. This is the full error:
> 
> ```
> MissingMethodException: Method not found: 'UnityEngine.Application.get_isWebPlayer'.
> Parse.ParseClient.Initialize (Configuration configuration)
> Parse.ParseClient.Initialize (System.String applicationId, System.String dotnetKey, System.String serverURL)
> Parse.ParseInitializeBehaviour.Initialize ()
> Parse.ParseInitializeBehaviour.Awake ()
> ```

hi there, so how did you fix this issue?

**Comment by brendanlk** [comment] 2019-02-05 02:04
> @brendanlk hi , so how did you fix this issue?

We have put all of the source from latest repo into our unity project. It's a bit clunky to have all the source in the project, and we are getting lots of warnings of deprecated WWW usages (we are using unity 2018.3), but it otherwise runs fine.

**Comment by TobiasPott** [comment] 2019-03-01 16:09
Could this one be considered closed?
The issue itself is Unity specific and the latest version of the repository no longer targets unity as a specific supported platform aside from basic .NET Standard support.

I think this one might come up again in the future, it might do so in context to unity specific implementations or changes.

**Comment by vaspotapov** [comment] 2019-03-04 06:10
Hi! Sorry, yes, this issue is considered to be closed.

**Closed** 2019-03-04 06:58 UTC
