### ISSUE TITLE
Package Parse 1.7.0 is not compatible with netcoreapp1.0

### ISSUE THREAD

**Issue by zayats77** [parse-community/Parse-SDK-dotNET#241] opened 2016-10-19 16:42 UTC

**Comment by alexbechmann** [comment] 2017-05-08 19:35
+1

**Comment by montymxb** [comment] 2017-12-03 04:28
Closing as no details provided. Can't really address this fully by just the title. If this is still issue please provide an adequate description of what the issue is and we can open this back up.

**Closed by montymxb** 2017-12-03 04:28 UTC
