### ISSUE TITLE
System.Net.WebException crash when there's no Internet connection. Windows 10 UWP

### ISSUE THREAD

**Issue by SalehAlbuga** [parse-community/Parse-SDK-dotNET#109] opened 2015-12-03 12:12 UTC
The sdk throws System.Net.WebException when there's no Internet connection. 
Here is the stack trace. Note that I'm using the source from pull request #91 to be able to work on Windows 10.

Here is the Stack Trace:

```
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Parse.Internal.InternalExtensions.<>c__DisplayClass13_0`1.<OnSuccess>b__0(Task t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute() 
```

**Comment by richardjrossiii** [comment] 2015-12-03 20:34
Hey @SamAlbuga. Marking this as 'wont fix' until #91 is merged in. Once it's in the SDK I'll take another look at this issue (I'll also need to get access to Windows 10 at some point... lol).

**Comment by Julien-Mialon** [comment] 2016-01-18 12:33
Hello @SamAlbuga I just looked on your issue, I can reproduce this exception when I'm calling ParseInstallation.SaveAsync method.

@richardjrossiii I just checked with last nuget package for Windows 8, it's the exact same behavior.

**Comment by richardjrossiii** [comment] 2016-01-19 18:31
@Julien-Mialon Ok, thanks. I'll take another look at this.

**Comment by SamAlbuga** [comment] 2016-01-24 14:59
@Julien-Mialon @richardjrossiii Thank you

**Comment by TobiasPott** [comment] 2020-06-28 16:32
This issue is most likely outdated and will be closed due to inactivity.
If you encounter any problem with the latest version from the main branch feel free to create a new issue to discuss possible solutions.

**Closed by TobiasPott** 2020-06-28 16:32 UTC
Labels: needs investigation
