### ISSUE TITLE
ParseUser.CurrentUser deadlock

### ISSUE THREAD

**Issue by rihadavid** [parse-community/Parse-SDK-dotNET#32] opened 2015-10-10 16:44 UTC
After updating to Parse.iOS 1.6, calling ParseUser.CurrentUser causes 10-30 seconds deadlock on first call - I can't do anything, UI doesn't respond even when I call this in background. After 10-30 seconds it returns null which is right (I'm not and was not logged in, clear installation).

I suppose it doesn't matter, but: I am calling this in UIViewController's ViewWillAppear() method. This controller is one of 3 tabs of UITabBarController. The UIViewController is first controller showed after app launch.

Downgrading to Parse.iOS 1.5.5 solved the issue.

**Comment by richardjrossiii** [comment] 2015-10-12 18:47
A stack trace would be super helpful here, I think. If you can manage to get us one, or a project that reproduces the issue, that would be great.

**Comment by rihadavid** [comment] 2015-10-12 23:47
It's not happening anymore, but I did not change a thing, just downloaded the solution again and reinstalled nuget (but I did clean&rebuild and nuget reinstall before and it did not help) .. strange. If I encounter the issue again I will try to give you the stacktrace for sure. Thanks for now

**Comment by rihadavid** [comment] 2015-10-12 23:55
Oh sorry, in the previous post I tried with 1.5.5 - now with 1.6.0 the issue is here again (on iPhone 4 iOS 7.1.2 device!) and here is the stack trace, hope it helps:
2015-10-13 01:52:15.141 AppNameiOS[5484:60b]    at AppName.iOS.Controllers.HomeViewController+<Appear>d__42.MoveNext()
2015-10-13 01:52:15.156 AppNameiOS[5484:60b]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(AppName.iOS.Controllers.<Appear>d__42 ByRef stateMachine)
2015-10-13 01:52:15.170 AppNameiOS[5484:60b]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start(AppName.iOS.Controllers.<Appear>d__42 ByRef stateMachine)
2015-10-13 01:52:15.174 AppNameiOS[5484:60b]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start(AppName.iOS.Controllers.<Appear>d__42 ByRef stateMachine)
2015-10-13 01:52:15.177 AppNameiOS[5484:60b]    at AppName.iOS.Controllers.HomeViewController.Appear()
2015-10-13 01:52
:15.180 AppNameiOS[5484:60b]    at AppName.iOS.Controllers.HomeViewController+<ViewWillAppear>d__38.MoveNext()
2015-10-13 01:52:15.183 AppNameiOS[5484:60b]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(AppName.iOS.Controllers.<ViewWillAppear>d__38 ByRef stateMachine)
2015-10-13 01:52:15.195 AppNameiOS[5484:60b]    at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start(AppName.iOS.Controllers.<ViewWillAppear>d__38 ByRef stateMachine)
2015-10-13 01:52:15.203 AppNameiOS[5484:60b]    at AppName.iOS.Controllers.HomeViewController.ViewWillAppear(Boolean animated)
2015-10-13 01:52:15.217 AppNameiOS[5484:60b]    at UIKit.UIApplication.UIApplicationMain(Int32 , System.String[] , IntPtr , IntPtr )
2015-10-13 01:52:15.220 AppNameiOS[5484:60b]    at UIKit.UIApplication.Main(System.String[] args, IntPtr principal, IntPtr delegate)
2015-10-13 01:52:15.224 AppNameiOS[5484:60b]    at UIKit.UIApplication.Main(System.String[] args, System.String principalClassName, System.String delegateClassName)
2015-10-13 01:52:15.227 AppNameiOS[5484:60b]    at AppName.iOS.Application.Main(System.String[] args)
2015-10-13 01:52:15.230 AppNameiOS[5484:60b] before user //now I'm calling if (ParseUser.CurrentUser != null)
Thread started: <Thread Pool> #8
Thread finished: <Thread Pool> #8
Thread finished: <Thread Pool> #8
Thread started: <Thread Pool> #9
Thread started: <Thread Pool> #10
Thread started: <Thread Pool> #11
Thread started: <Thread Pool> #12
Thread started: <Thread Pool> #13
Thread started: <Thread Pool> #14
Thread started: <Thread Pool> #15
Thread started: <Thread Pool> #16
Thread started: <Thread Pool> #17
Thread started: <Thread Pool> #18
2015-10-13 01:52:25.862 AppNameiOS[5484:60b] after user //now it continues
2015-10-13 01:52:25.885 AppNameiOS[5484:60b]    at AppName.iOS.Controllers.HomeViewController+<Appear>d__42.MoveNext()
2015-10-13 01:52:25.890 AppNameiOS[5484:60b]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(AppName.iOS.Controllers.<Appear>d__42 ByRef stateMachine)
2015-10-13 01:52:25.892 AppNameiOS[5484:60b]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start(AppName.iOS.Controllers.<Appear>d__42 ByRef stateMachine)
2015-10-13 01:52:25.895 AppNameiOS[5484:60b]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start(AppName.iOS.Controllers.<Appear>d__42 ByRef stateMachine)
2015-10-13 01:52:25.898 AppNameiOS[5484:60b]    at AppName.iOS.Controllers.HomeViewController.Appear()
2015-10-13 01:52:25.900 AppNameiOS[5484:60b]    at AppName.iOS.Controllers.HomeViewController+<ViewWillAppear>d__38.MoveNext()
2015-10-13 01:52:25.9
03 AppNameiOS[5484:60b]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start(AppName.iOS.Controllers.<ViewWillAppear>d__38 ByRef stateMachine)
2015-10-13 01:52:25.906 AppNameiOS[5484:60b]    at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start(AppName.iOS.Controllers.<ViewWillAppear>d__38 ByRef stateMachine)
2015-10-13 01:52:25.911 AppNameiOS[5484:60b]    at AppName.iOS.Controllers.HomeViewController.ViewWillAppear(Boolean animated)
2015-10-13 01:52:25.913 AppNameiOS[5484:60b]    at UIKit.UIApplication.UIApplicationMain(Int32 , System.String[] , IntPtr , IntPtr )
Thread started:  #19
2015-10-13 01:52:25.916 AppNameiOS[5484:60b]    at UIKit.UIApplication.Main(System.String[] args, IntPtr principal, IntPtr delegate)
2015-10-13 01:52:25.918 AppNameiOS[5484:60b]    at UIKit.UIApplication.Main(System.String[] args, System.String principalClassName, System.String delegateClassName)
2015-10-13 01:52:25.920 AppNameiOS[5484:60b]    at AppName.iOS.Application.Main(System.String[] args)

**Comment by rihadavid** [comment] 2016-02-15 01:08
I updated from 1.5.5 to latest version and the deadlock is still present. There was no problem until I uninstalled the app completely from the device and launched clear installation - now the app hangs on calling ParseUser.CurrentUser forever.

I've looked into open source code and in public static ParseUser CurrentUser there is comment "// TODO (hallucinogen): this will without a doubt fail in Unity. How should we fix it?" .. well, I believe this is what it fails on my Xamarin iOS app. I used to have a few others .Wait() calls in my app and over time I removed all of them because they all caused a deadlock eventually. Would it be possible to avoid this sync wait? Could you look back into version 1.5.5 and check what has changed from 1.5.5 to 1.6.0?

Not much stuff happens before I call the ParseUser.CurrentUser, it is called right as the UI appears. Maybe some SQLite calls or something might be called before this. I will continue with my investigation. Is there anything I could do to help you solve this?

I am running my app on iOS 7.1.2 (11D257) iPhone 4.

**Comment by rihadavid** [comment] 2016-02-15 18:06
@richardjrossiii today I've done some investigation but I was not able to distinguish what is causing the deadlock. If I remove mostly everything from my app, it is not happening, when I am removing code step by step, it sometimes happens and sometimes not. I mean if I remove some particular line of code, it doesn't happen one time but happens another, the behavior is not consistent. From what I've read on stackoverflow I think that using .Wait() is generally not very good practice and it is causing deadlock from various reasons, dependent on various application states.

However I've found a workaround for this issue:
`var parseCurrentUser = await RunBlockingFuncOnOtherThread(() => ParseUser.CurrentUser, 15000);`

    public static async Task<T> RunBlockingFuncOnOtherThread<T>(Func<T> function, int msTimeout)
        {
            var tcs = new TaskCompletionSource<T>();
            new System.Threading.Thread(async () =>
            {
                T result = function.Invoke();
                if (!tcs.Task.IsCompleted)
                    tcs.TrySetResult(result);
            }).Start();

            Task.Run(async () =>
            {
                await Task.Delay(msTimeout);
                if (!tcs.Task.IsCompleted)
                {
                    Console.WriteLine("RunBlockingFuncOnOtherThread() timed out");
                    tcs.TrySetResult(default(T));
                }
            });

            return await tcs.Task;
        }
When I use this for all ParseUser.CurrentUser calls (except those in sync methods), the deadlock does not happen on app start and RunBlockingFuncOnOtherThread() never times out, all calls are finished in a few seconds.

**Comment by richardjrossiii** [comment] 2016-02-16 18:48
Yeah, this is most likely due to poor OS thread scheduling and the fact that ParseUser.CurrentUser requires a 'wait' call. We really need to  make an async version of `CurrentUser`, and deprecate the synchronous one.

**Comment by rihadavid** [comment] 2016-02-16 19:05
Ok, thanks for reopening. BTW I've just found #50 which is probably duplicate of this.

**Comment by TobiasPott** [comment] 2020-06-28 15:54
I close this issue due to the deprecated SDK used in the description and the availability of general support on iOS (via Xamarin or Unity) in the latest version in the master branch.

**Closed by TobiasPott** 2020-06-28 15:54 UTC
Labels: bug, needs investigation
