### ISSUE TITLE
Issues with parse-server behind Lets Encrypt https proxy, but only Android

### ISSUE THREAD

**Issue by danibjor** [parse-community/Parse-SDK-dotNET#243] opened 2016-11-23 13:27 UTC
We try to use the Parse DotNet SDK with Xamarin to fetch data from a local Parse installation.

Setup works fine and we can browse the data with ParseDashboard over https.

The .NET solution consists of a shared project, and an Android and iOS client. 

In the shared code, we init parse and do a simple test save object. This works fine on iOS but not with Android. If we switch to http, then the Android client also saves just fine.

Problem is that there are no exceptions thrown when I debug the solution on Android (Samsung Galaxy S7 Edge, Android 6.0) - I just newer get a response back from the server.

Debugging the same project in the iOS simulator saves the test-object just fine. Switching to http makes the android client play nice too...

We are using Lets Encrypt SSL certificates in the proxy before the Parse Server.

So, what is going on?

Edit: 
All keys are provided on the Parse Server. Xamarin project uses both AppID and WindowsKey
Server 2.2.24, SDK 1.7

**Comment by richardjrossiii** [comment] 2016-11-29 17:39
Is it possible that the android device doesn't have the Lets Encrypt Root CA in its trust store? That would make any HTTPS connection to a lets-encrypt signed cert fail.

**Comment by montymxb** [comment] 2017-12-03 04:24
Closing as the above mentioned solution is _likely_ the cause. If this is still an issue, and you have verified the CA root for LetsEncrypt is trusted, let us know and we'll look at this again.

**Closed by montymxb** 2017-12-03 04:24 UTC
